version: '3'
services:

  server:
    build: ./code-server
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=TEST
    volumes:
      - ./serverdata:/config
    ports:
      - 8443:8443
    restart: unless-stopped
